---

# Here we will define our default issuer
# for the ACME challenges
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: default-issuer

spec:
  acme:
    email: shaadx@protonmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: default-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
