---

# Let's set up our ingress nginx
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: ingres-nginx

spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.7.1
    # Here we use an helm chart to configure our ingress so let's
    # specify our values
    helm:
      values: |
        controller:
          watchIngressWithoutClass: true
          ingressClass: "public"
          ingressClassResource:
            enabled: true
            default: true
            name: "public"
          config:
            forwarded-for-header: "true"
            use-http2: "true"
