# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  labels:
    app: local-path-storage

spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: local-path-storage
  project: default
  source:
    repoURL: https://charts.rancher.io
    chart: local-path-provisioner
    targetRevision: v0.0.26
    helm:
      values: |
        storageClass.defaultClass: true
        nodePathMap: [{node DEFAULT_PATH_FOR_NON_LISTED_NODES, paths: [/opt/node-storage]}]
