---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  labels:
    app: local-path-storage

spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: local-path-storage
  project: default
  source:
    repoURL: https://github.com/shaadx-coding/infrastructure-shaadx.git
    targetRevision: k8s
    path: k8s/manifests/local-path-provisioner
