---

# Let's define here the vault
# secret operator that will allow us to use
# vault as our secret manager for our k8s infrastructure
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: vault-secrets-operator

spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: vault-secrets-operator
  project: default
  source:
    repoURL: https://ricoberger.github.io/helm-charts/
    chart: vault-secrets-operator
    targetRevision: 2.4.0
    helm:
      values: |
        vault:
          address: https://vault.shaadx.com
          authMethod: kubernetes
